// Settlement — one site turned into a living place: plan → architecture →
// ground → lights → shadows → colliders → POIs → people & traffic.
//
// Geometry is generated by a time-sliced generator (build()) so distant towns
// stream in without hitches; the capital is built synchronously at load.
// Architecture is split into ~128 m tiles (one draw call each, frustum- and
// shadow-culled), everything lives in the SiteFrame group.

import * as THREE from 'three';
import { MeshBuilder } from './builder.js';
import { makeCivMaterial, makeCatcherMaterial, makeGlowMaterial, makeGlowMesh, CityShadow, createCivUniforms } from './materials.js';
import { SiteFrame } from './frame.js';
import { planSettlement, KIND_RADIUS } from './layout.js';
import { ribbon, disc, rect, LampField, catcherGeometry } from './ground.js';
import { G } from './ids.js';
import { Random, seedFrom } from '../../../core/Random.js';
import { STYLES } from './styles/index.js';
import { pads as spaceportPads } from './styles/outpost.js';
import { People } from './people.js';
import { Traffic } from './traffic.js';
import { inscription } from './lore.js';
import { plantTrees } from './trees.js';

const TILE = 128;
// far-LOD silhouette heights per style (m) and which styles get pitched roofs
const SIL_H = { pastoral: [6, 10], temple: [5, 8], monolithic: [8, 34], organic: [7, 14], outpost: [3.5, 7], gothic: [8, 13], neon: [14, 70], ruins: [2, 8] };
const PITCHED = new Set(['pastoral', 'temple', 'gothic']);
function prismGeometry() {
  const P = [-0.5, 0, -0.5, 0.5, 0, -0.5, 0.5, 0, 0.5, -0.5, 0, 0.5, -0.5, 1, 0, 0.5, 1, 0];
  const I = [3, 2, 5, 3, 5, 4, 1, 0, 4, 1, 4, 5, 2, 1, 5, 0, 3, 4];
  const pos = [];
  for (const i of I) pos.push(P[i * 3], P[i * 3 + 1], P[i * 3 + 2]);
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.computeVertexNormals();
  return g;
}
const _v = new THREE.Vector3(), _m = new THREE.Matrix4(), _q = new THREE.Quaternion(), _s = new THREE.Vector3();

export class Settlement {
  constructor(civ, site, opts = {}) {
    this.civ = civ;
    this.level = civ.level;
    this.world = civ.level.world;
    this.site = site;
    this.main = !!opts.main;
    this.styleKey = site.kind === 'ruins' ? 'ruins' : (site.style || 'pastoral');
    this.style = STYLES[this.styleKey] || STYLES.pastoral;
    // the capital is promoted one size up: every world gets one memorable town
    const up = { village: 'town', outpost: 'village', town: 'city', city: 'city', megacity: 'megacity', spaceport: 'spaceport', ruins: 'ruins' };
    this.kind = this.main ? (up[site.kind] || site.kind) : site.kind;
    this.seed = seedFrom(this.level.planet.seed, 'civ', site.index);
    this.frame = new SiteFrame(this.world, site);
    this.group = this.frame.group;
    this.group.name = `civ:${site.name}`;
    this.uniforms = createCivUniforms(this.world, this.level.aesthetic?.palette || {});
    const A = this.level.aesthetic;
    this.uniforms.uCivSnow.value = A?.terrain?.style === 'glacial' || this.level.planet.kind === 'ice' ? 0.8 : 0;
    this.built = false;
    this.colliders = [];
    this.pois = [];
    this.anim = [];
    this.meshes = [];
    this.visible = true;
  }

  // ---------------------------------------------------------------- context given to style generators
  _makeCtx() {
    const self = this, frame = this.frame;
    const rng = new Random(this.seed);
    const tiles = new Map();
    let forced = null, cur = null;
    const tileFor = (x, z) => {
      const key = forced || `${Math.floor(x / TILE)},${Math.floor(z / TILE)}`;
      let t = tiles.get(key);
      if (!t) { t = new MeshBuilder(8192); tiles.set(key, t); }
      return t;
    };
    const occ = [];
    const ctx = {
      settlement: this, frame, rng, world: this.world, plan: null, pal: null, A: this.level.aesthetic, main: this.main,
      M: new THREE.Matrix4(), glows: [], beacons: [], lamps: [], anim: this.anim, footprints: [], landmarkSpots: [], group: this.group, tiles,
      get B() { return cur || (cur = tileFor(0, 0)); },
      select(x, z) { cur = tileFor(x, z); return cur; },
      useTile(key) { forced = key; if (key) cur = tileFor(0, 0); },
      place(x, z, h, yaw = 0) {
        if (!forced) cur = tileFor(x, z);
        frame.placement(x, z, h, yaw, ctx.M);
        cur.setMatrix(ctx.M);
        return ctx.M;
      },
      inv() { return ctx.M.clone().invert(); },
      collider(cx, cy, cz, hx, hy, hz, walkable = true) {
        // on sloped lots extend the box down to the lowest ground under the plinth
        const lot = ctx.lot;
        if (lot && lot.low != null) {
          const bottom = (lot.low - lot.base) - 0.4;
          if (cy - hy > bottom) { const top = cy + hy; hy = (top - bottom) / 2; cy = (top + bottom) / 2; }
        }
        const c = _v.set(cx, cy, cz).applyMatrix4(ctx.M).applyMatrix4(frame.matrix).clone();
        _m.multiplyMatrices(frame.matrix, ctx.M); _m.decompose(_s, _q, _s);
        self.colliders.push({ type: 'box', center: c, quaternion: _q.clone(), half: new THREE.Vector3(hx, hy, hz), walkable });
      },
      free(x, z, r, onPlaza = false) {
        const q = ctx.plan.roadGrid.query(x, z, r + 8);
        if (!onPlaza && q.d < r) return false;
        if (frame.wet(x, z)) return false;
        for (const o of occ) if (Math.hypot(o[0] - x, o[1] - z) < o[2] + r) return false;
        const hits = ctx.plan.lotGrid.hits({ x, z, w: r * 2, d: r * 2, yaw: 0, pad: 0 });
        if (hits && !onPlaza) return false;
        if (onPlaza) {
          // only plaza reservations may overlap
          for (const l of ctx.plan.lots) if (Math.abs(l.x - x) < l.w + r && Math.abs(l.z - z) < l.w + r && Math.hypot(l.x - x, l.z - z) < Math.hypot(l.w, l.d) / 2 + r) return false;
        }
        return true;
      },
      occupy(x, z, r) { occ.push([x, z, r]); },
      poiAt(x, z, h, radius, kind, title) {
        self.pois.push({ x, z, h, radius, kind, title });
      },
      dynamicBuilder() {
        const B = new MeshBuilder(1024);
        return {
          B,
          finish() {
            const mesh = new THREE.Mesh(B.toGeometry(), self.dynMaterial);
            mesh.castShadow = true; mesh.receiveShadow = true;
            mesh.matrixAutoUpdate = false;
            self.group.add(mesh); self.meshes.push(mesh);
            return mesh;
          },
        };
      },
    };
    return ctx;
  }

  /** Plan only (cheap, ~50–100 ms): context, palette, reserved zones, street plan. Idempotent. */
  prepare() {
    if (this.plan) return;
    const S = this.style;
    const ctx = this._makeCtx();
    this.ctx = ctx;
    ctx.pal = S.palette(this.level.aesthetic, ctx.rng);
    const radius = KIND_RADIUS[this.kind] ?? 220;
    const reserve = S.reserve ? S.reserve(ctx, radius) : [];
    const plan = planSettlement(this.frame, this.styleKey, this.kind, this.seed, { main: this.main, radius, reserve });
    ctx.plan = plan;
    this.plan = plan;
  }

  /** Time-sliced build. Yields periodically; run to completion with buildNow(). */
  *build() {
    const t0 = performance.now();
    const S = this.style, frame = this.frame;
    this.prepare();
    const ctx = this.ctx, rng = ctx.rng, plan = this.plan;
    yield;
    // materials
    const engine = this.level.engine;
    this.material = makeCivMaterial(this.uniforms, 'building');
    this.dynMaterial = makeCivMaterial(this.uniforms, 'building', { dynamic: true });
    this.groundMaterial = makeCivMaterial(this.uniforms, 'ground', { pull: 0.0012 });

    // architecture
    let k = 0;
    for (const lot of plan.lots) {
      ctx.select(lot.x, lot.z);
      ctx.lot = lot;
      S.building(ctx, lot);
      ctx.lot = null;
      if (++k % 24 === 0) yield;
    }
    for (const pz of plan.plazas) { S.plaza(ctx, pz); }
    yield;
    S.extras?.(ctx);
    if (this.kind === 'spaceport' && this.styleKey !== 'outpost') spaceportPads(ctx, this.main ? 6 : 4);
    yield;
    this.trees = plantTrees(this, ctx);
    yield;
    if (this.main) S.landmark?.(ctx);
    yield;
    if (plan.wall && S.wall) S.wall(ctx, plan.wall, plan.gates);
    yield;

    // meshes per tile
    for (const [key, B] of ctx.tiles) {
      if (B.n === 0) continue;
      const mesh = new THREE.Mesh(B.toGeometry(), this.material);
      mesh.name = `civ-tile:${key}`;
      // city-scale sun shadows come from CityShadow; casting into the engine cascades only near the player
      mesh.castShadow = false; mesh.receiveShadow = true;
      mesh.matrixAutoUpdate = false;
      this.group.add(mesh); this.meshes.push(mesh);
      this.archMeshes = this.archMeshes || [];
      this.archMeshes.push(mesh);
      B.clear();
    }
    yield;

    // ground
    const lamps = new LampField(ctx.lamps);
    const Gb = new MeshBuilder(16384);
    Gb.ext(1, 0, 0, 0);
    const gp = ctx.pal.ground;
    const c = plan.center;
    // dirt shoulders under everything, then the paving
    for (const road of plan.roads) {
      const zone = Math.hypot(road.pts[0][0] - c[0], road.pts[0][1] - c[1]) / plan.radius;
      ribbon(Gb, frame, road.pts, road.w + 1.6, G.DIRT, gp.dirt, 0.12, lamps, 0.3);
      void zone;
    }
    for (const road of plan.roads) {
      const mid = road.pts[Math.floor(road.pts.length / 2)];
      const zone = Math.hypot(mid[0] - c[0], mid[1] - c[1]) / plan.radius;
      const id = S.roadMat(road, zone);
      const color = road.kind === 'main' || road.kind === 'avenue' ? gp.main : road.kind === 'street' ? gp.street : gp.lane;
      ribbon(Gb, frame, road.pts, road.w, id, id === G.DIRT ? gp.dirt : color, 0.2, lamps, rng.float());
    }
    yield;
    for (const pz of plan.plazas) disc(Gb, frame, pz.x, pz.z, pz.r, S.plazaMat(pz), gp.plaza, 0.26, lamps, { seed: rng.float() });
    for (const f of plan.fields) rect(Gb, frame, f.x, f.z, f.w, f.d, f.yaw, G.FIELD, ctx.pal.fields?.[f.kind % ctx.pal.fields.length] || gp.dirt, 0.1, null, { seed: rng.float(), edge: 0.5, step: 5 });
    for (const g of ctx.groundExtra || []) g(Gb, lamps);
    if (Gb.n) {
      const gm = new THREE.Mesh(Gb.toGeometry(), this.groundMaterial);
      gm.receiveShadow = true; gm.matrixAutoUpdate = false; gm.renderOrder = 1;
      gm.name = 'civ-ground';
      this.group.add(gm); this.meshes.push(gm);
    }
    yield;

    // shadow catcher (terrain receives city shadows + contact occlusion)
    const bR = plan.builtRadius + 40;
    const lotsH = plan.lots.map((l) => ({ ...l, h: 8 }));
    const cg = catcherGeometry(frame, c[0], c[1], bR, lotsH, engine.quality.pick(5, 4, 3, 3));
    this.catcherMat = makeCatcherMaterial(this.uniforms);
    const catcher = new THREE.Mesh(cg, this.catcherMat);
    catcher.matrixAutoUpdate = false; catcher.renderOrder = 2; catcher.frustumCulled = true;
    this.group.add(catcher); this.meshes.push(catcher);
    yield;

    // glows
    this.glowMat = makeGlowMaterial(this.uniforms, { size: 1.0, minPx: 1.6, gain: 7 });
    if (ctx.glows.length) {
      this.glowMesh = makeGlowMesh(this.glowMat, ctx.glows);
      this.glowMesh.matrixAutoUpdate = false;
      this.group.add(this.glowMesh); this.meshes.push(this.glowMesh);
    }
    if (ctx.beacons.length) {
      this.beaconMat = makeGlowMaterial(this.uniforms, { size: 1.0, minPx: 2.2, gain: 9, dayVis: 0.6 });
      this.beaconMesh = makeGlowMesh(this.beaconMat, ctx.beacons);
      this.beaconMesh.matrixAutoUpdate = false;
      this.group.add(this.beaconMesh); this.meshes.push(this.beaconMesh);
    }
    yield;

    // city shadow
    const sm = engine.quality.pick(1024, 2048, 2048, 4096);
    this.shadow = new CityShadow(engine.renderer, sm, this.uniforms);
    this.shadow.setBounds(new THREE.Vector3(c[0], frame.hAt(c[0], c[1]) - frame.h0, c[1]), plan.builtRadius + 60);
    for (const m of this.archMeshes || []) this.shadow.addCaster(m);
    for (const m of this.trees?.meshes || []) this.shadow.addCaster(m);

    // life
    if (this.style.people !== false) {
      this.people = new People(this, ctx);
      yield;
    }
    this.traffic = new Traffic(this, ctx);
    yield;

    // colliders & POIs
    for (const col of this.colliders) this.world.addCollider(col);
    this._makePOIs(ctx);
    this.built = true;
    this.lod = null;
    this.buildMs = performance.now() - t0;
    ctx.glows = null; ctx.lamps = null;
  }

  /**
   * Far LOD (also stands in for settlements not built yet): one instanced box
   * per lot (+ gable prisms for pitched-roof styles) and a warm light per lot
   * for the night side. Cheap: two draw calls, a few hundred instances.
   */
  makeFarLOD() {
    if (this.farGroup) return;
    this.prepare();
    const f = this.frame, plan = this.plan, pal = this.ctx.pal;
    const rng = new Random(seedFrom(this.seed, 'far'));
    const lots = plan.lots;
    const g = new THREE.Group();
    g.matrixAutoUpdate = false;
    g.name = 'civ-far';
    this.farGroup = g;
    this.group.add(g);
    if (!lots.length) return;
    const H = SIL_H[this.styleKey] || [6, 10];
    const walls = pal.walls || pal.concrete || pal.towers || pal.panels || pal.shells || pal.stones || [new THREE.Color('#bbbbbb')];
    const roofs = PITCHED.has(this.styleKey) ? pal.roofs : null;
    const box = new THREE.BoxGeometry(1, 1, 1); box.translate(0, 0.5, 0);
    this.farMat = new THREE.MeshStandardMaterial({ roughness: 0.92, metalness: 0 });
    const bm = new THREE.InstancedMesh(box, this.farMat, lots.length);
    const rm = roofs ? new THREE.InstancedMesh(prismGeometry(), this.farMat, lots.length) : null;
    const M4 = new THREE.Matrix4(), S4 = new THREE.Matrix4(), c = new THREE.Color();
    const lamp = new THREE.Color(this.level.aesthetic?.palette?.lights || '#ffcf87');
    const items = [];
    for (let i = 0; i < lots.length; i++) {
      const l = lots[i];
      const core = 1 - Math.min(1, l.zone ?? 0.5);
      const h = rng.range(H[0], H[1]) * (0.7 + 0.6 * core);
      const drop = (l.base - (l.low ?? l.base)) + 0.5;
      f.placement(l.x, l.z, l.base - drop, l.yaw, M4);
      M4.multiply(S4.makeScale(l.w * 0.85, h + drop, l.d * 0.85));
      bm.setMatrixAt(i, M4);
      bm.setColorAt(i, c.copy(walls[i % walls.length]).multiplyScalar(0.9));
      if (rm) {
        f.placement(l.x, l.z, l.base + h, l.yaw, M4);
        M4.multiply(S4.makeScale(l.w * 0.95, Math.min(l.w, l.d) * 0.45, l.d * 0.95));
        rm.setMatrixAt(i, M4);
        rm.setColorAt(i, c.copy(roofs[i % roofs.length]));
      }
      if (rng.chance(0.75)) items.push({ position: f.point(l.x + rng.range(-2, 2), l.z + rng.range(-2, 2), l.base + rng.range(2, Math.max(2.5, h * 0.8))), color: lamp.clone().multiplyScalar(rng.range(0.6, 1.2)), scale: rng.range(1.2, 2.2), phase: rng.float() });
    }
    for (const m of [bm, rm]) {
      if (!m) continue;
      m.instanceMatrix.needsUpdate = true; if (m.instanceColor) m.instanceColor.needsUpdate = true;
      m.matrixAutoUpdate = false; m.receiveShadow = false; m.castShadow = false;
      m.computeBoundingSphere();
      g.add(m);
    }
    if (items.length) {
      this.farGlowMat = makeGlowMaterial(this.uniforms, { size: 1.0, minPx: 1.2, gain: 5 });
      const gl = makeGlowMesh(this.farGlowMat, items);
      gl.matrixAutoUpdate = false; gl.frustumCulled = false;
      g.add(gl);
    }
  }

  /** 'detail' | 'far' | 'none' */
  setLOD(lod) {
    if (this.lod === lod) return;
    this.lod = lod;
    const detail = lod === 'detail' && this.built;
    for (const m of this.meshes) m.visible = detail;
    if (this.people?.mesh) this.people.mesh.visible = detail;
    for (const m of this.traffic?.meshes || []) m.visible = detail;
    if (this.farGroup) this.farGroup.visible = lod === 'far' || (lod === 'detail' && !this.built);
  }

  buildNow() { const g = this.build(); while (!g.next().done) { /* run */ } }

  _makePOIs(ctx) {
    const P = this.level.planet, f = this.frame;
    const rng = new Random(seedFrom(this.seed, 'lore'));
    const add = (x, z, h, radius, kind, title, text) => {
      const pos = f.point(x, z, h).applyMatrix4(f.matrix);
      this.world.addPOI({ position: pos, radius, title, text, kind });
    };
    const c = this.plan.center;
    add(c[0], c[1], f.hAt(c[0], c[1]) + 1.5, Math.max(30, this.plan.plazas[0].r * 1.6), 'settlement', this.site.name,
      inscription(rng, 'settlement', { planet: P, site: this.site, style: this.styleKey, kind: this.kind }));
    // every lesser square keeps a shrine, a statue or a mural with its own small story
    const titles = { pastoral: ['The Weathervane Shrine', 'The Founders\' Fountain', 'The Mural of the Long Summer'], temple: ['The Shrine of the Falling Maple', 'The Stone of Stillness', 'The Bell of the Mountain Monks'], monolithic: ['The Water Shrine', 'The Obelisk of Patience', 'The Wall of Names'], organic: ['The Listening Pool', 'The Seed Shrine', 'The Lumen Garden'], outpost: ['The First Landing Plaque', 'The Memorial Antenna', 'The Greenhouse Shrine'], gothic: ['The Oath Stone', 'The Chapel of the Gilded Haze', 'The Pilgrim\'s Statue'], neon: ['The Shrine of the Night Crews', 'The Rain Mural', 'The Last Jukebox'], ruins: ['The Worn Altar', 'The Face in the Stone', 'The Broken Stair'] }[this.styleKey] || ['A Shrine'];
    this.plan.plazas.slice(1).forEach((pz, i) => {
      add(pz.x, pz.z, f.hAt(pz.x, pz.z) + 1.5, Math.max(14, pz.r * 1.4), 'shrine', titles[i % titles.length],
        inscription(rng, 'shrine', { planet: P, site: this.site, style: this.styleKey }));
    });
    for (const p of this.pois) {
      add(p.x, p.z, p.h, p.radius, p.kind, p.title, inscription(rng, p.kind, { planet: P, site: this.site, style: this.styleKey, title: p.title }));
    }
  }

  /** Per-frame update: LOD, shadows, animation, life. */
  update(dt, t, camLocal, camDist) {
    const detailR = this.main ? 14000 : 6000;
    const lod = camDist < detailR ? 'detail' : camDist < 90000 ? 'far' : 'none';
    this.setLOD(lod);
    if (!this.built || lod !== 'detail') return;
    const sunL = this.frame.sunLocal(this.world.sunDir, this.uniforms.uCivSunL.value);
    this.shadow.update(sunL, this.level.engine.shotMode && !this._shotShadowDone);
    if (this.level.engine.shotMode) this._shotShadowDone = true;
    for (const fn of this.anim) fn(t, dt);
    this.people?.update(dt, t, camLocal, camDist);
    this.traffic?.update(dt, t, camLocal, camDist);
  }

  forceShadow() { this._shotShadowDone = false; this.shadow?.update(this.frame.sunLocal(this.world.sunDir, this.uniforms.uCivSunL.value), true); }

  dispose() {
    for (const c of this.colliders) this.world.removeCollider(c);
    this.group.parent?.remove(this.group);
    for (const m of this.meshes) m.geometry?.dispose();
    this.material?.dispose(); this.dynMaterial?.dispose(); this.groundMaterial?.dispose();
    this.catcherMat?.dispose(); this.glowMat?.dispose(); this.beaconMat?.dispose(); this.farMat?.dispose(); this.farGlowMat?.dispose();
    this.farGroup?.traverse((o) => o.geometry?.dispose());
    this.trees?.dispose();
    this.shadow?.dispose();
    this.people?.dispose(); this.traffic?.dispose();
  }
}
