// The art direction of every world. Each aesthetic is a love letter to a
// director / artist / game, expressed as data that terrain, sky, flora,
// architecture, music and the color grade all read from.
//
// Colors are sRGB hex (THREE.Color converts to linear). Atmosphere `rayleigh`
// is a relative per-channel scattering weight (Earth ≈ [0.18, 0.42, 1.0]);
// `density` scales it. Planet kinds list which aesthetics fit them.

export const AESTHETICS = {
  dune: {
    name: 'Arrakeen', inspiration: 'Denis Villeneuve — Dune; Moebius dunes',
    mood: 'vast, sacred, silent; heat shimmer over endless dunes, brutalist monoliths',
    kinds: ['desert', 'barren'],
    palette: { sky: '#d9b48a', zenith: '#8a6a52', horizon: '#f2d2a6', fog: '#caa27a', sun: '#ffe2b8',
      ground: ['#c99a62', '#b07a48', '#8d5f3a', '#e0bb86'], rock: '#7c5a42', sand: '#d8ae76', water: '#3e5a5a',
      foliage: ['#6c6a3e', '#857a4a'], accent: '#ff9a3c', lights: '#ffb36b' },
    atmo: { rayleigh: [0.55, 0.42, 0.28], density: 1.0, mie: 0.9, mieColor: '#e8c49a', haze: 0.7 },
    terrain: { style: 'dunes', relief: 0.55, ocean: 0.0, roughness: 0.4 },
    architecture: 'monolithic', flora: 'sparse', fauna: ['worms', 'birds'], weather: ['dust', 'clear'],
    grade: { temperature: 0.25, contrast: 1.12, saturation: 0.86, shadowsTint: [0.02, 0.0, -0.01], highlightsTint: [0.02, 0.01, -0.02] },
    music: { root: 50, scale: 'phrygian', tempo: 54, timbre: 'drone' },
  },
  ghibli: {
    name: 'Laputa', inspiration: 'Hayao Miyazaki — Laputa, Nausicaä, Howl; Studio Ghibli skies',
    mood: 'pastoral wonder; cumulus towers, wind through tall grass, white towns with red roofs, windmills',
    kinds: ['terran', 'ocean', 'jungle'],
    palette: { sky: '#7fb8ec', zenith: '#3b7dd8', horizon: '#d6ecff', fog: '#bcd8ee', sun: '#fff4dc',
      ground: ['#6fa34a', '#4f8a3a', '#8bb85a', '#b9c97a'], rock: '#8a8478', sand: '#e6d7a8', water: '#2a7fa8',
      foliage: ['#4e9a3c', '#6cb84a', '#2f7a34', '#9acb5a'], accent: '#d8432f', lights: '#ffcf87' },
    atmo: { rayleigh: [0.18, 0.42, 1.0], density: 1.0, mie: 0.25, mieColor: '#ffffff', haze: 0.25 },
    terrain: { style: 'rolling', relief: 0.65, ocean: 0.35, roughness: 0.5 },
    architecture: 'pastoral', flora: 'lush', fauna: ['birds', 'grazers', 'fish'], weather: ['clear', 'cumulus', 'rain'],
    grade: { temperature: 0.08, contrast: 1.04, saturation: 1.12, lift: [0.01, 0.012, 0.02] },
    music: { root: 60, scale: 'lydian', tempo: 76, timbre: 'strings' },
  },
  moebius: {
    name: 'Arzach', inspiration: 'Moebius (Jean Giraud) — Arzach, The Airtight Garage; Laloux — Fantastic Planet',
    mood: 'dreamlike pastel deserts, impossible organic towers, flat clean light, uncanny calm',
    kinds: ['desert', 'exotic', 'barren'],
    palette: { sky: '#f3c9b6', zenith: '#8fc4c8', horizon: '#fde6d2', fog: '#f0d0c0', sun: '#fffaf0',
      ground: ['#e9b8a0', '#d99a8a', '#f2d3b0', '#c98f8f'], rock: '#b07c86', sand: '#f4d6b8', water: '#5fb3b3',
      foliage: ['#7fc4b0', '#e88a6a', '#c8e0a0'], accent: '#3fb0a6', lights: '#ffe0a0' },
    atmo: { rayleigh: [0.6, 0.45, 0.5], density: 0.85, mie: 0.35, mieColor: '#ffe8dc', haze: 0.35 },
    terrain: { style: 'mesas', relief: 0.8, ocean: 0.08, roughness: 0.35 },
    architecture: 'organic', flora: 'alien', fauna: ['walkers', 'jellies', 'birds'], weather: ['clear'],
    grade: { temperature: 0.05, contrast: 0.98, saturation: 1.0, lift: [0.02, 0.01, 0.015] },
    music: { root: 57, scale: 'dorian', tempo: 64, timbre: 'glass' },
  },
  kubrick: {
    name: 'Tycho', inspiration: 'Stanley Kubrick — 2001: A Space Odyssey; Arthur C. Clarke',
    mood: 'stark, clinical, monumental; black sky, white regolith, a monolith humming at the center',
    kinds: ['barren', 'ice'],
    palette: { sky: '#05060a', zenith: '#000000', horizon: '#1a1c22', fog: '#0a0b0f', sun: '#ffffff',
      ground: ['#bdbdbd', '#9a9a9a', '#d8d8d8', '#7a7a7a'], rock: '#6e6e6e', sand: '#cfcfcf', water: '#202020',
      foliage: ['#555555'], accent: '#ff2a2a', lights: '#f4f6ff' },
    atmo: { rayleigh: [0.2, 0.25, 0.3], density: 0.03, mie: 0.0, mieColor: '#ffffff', haze: 0.0 },
    terrain: { style: 'craters', relief: 0.6, ocean: 0.0, roughness: 0.6 },
    architecture: 'monolithic', flora: 'none', fauna: [], weather: ['clear'],
    grade: { temperature: -0.04, contrast: 1.22, saturation: 0.7, blackPoint: 0.01 },
    music: { root: 45, scale: 'aeolian', tempo: 40, timbre: 'choir' },
  },
  tarkovsky: {
    name: 'The Zone', inspiration: 'Andrei Tarkovsky — Stalker, Solaris; Annihilation',
    mood: 'wet, overgrown, holy decay; mist in birch forests, flooded ruins, a hum in the silence',
    kinds: ['terran', 'toxic', 'jungle'],
    palette: { sky: '#9aa59a', zenith: '#6b7a76', horizon: '#c4cbbf', fog: '#a7b0a2', sun: '#f2f0dc',
      ground: ['#4e5a3a', '#5f6b44', '#3f4a33', '#7a7a5a'], rock: '#5d5f58', sand: '#8a8670', water: '#3a4a40',
      foliage: ['#4a5e34', '#647a3e', '#2f3e28'], accent: '#c8b26a', lights: '#ffd28a' },
    atmo: { rayleigh: [0.3, 0.38, 0.42], density: 1.15, mie: 1.2, mieColor: '#d8ddd0', haze: 1.0 },
    terrain: { style: 'wetlands', relief: 0.35, ocean: 0.25, roughness: 0.55 },
    architecture: 'ruins', flora: 'boreal', fauna: ['birds', 'grazers'], weather: ['fog', 'rain'],
    grade: { temperature: -0.05, contrast: 1.02, saturation: 0.72, shadowsTint: [-0.01, 0.01, 0.0] },
    music: { root: 48, scale: 'aeolian', tempo: 46, timbre: 'drone' },
  },
  ueda: {
    name: 'The Forbidden Land', inspiration: 'Fumito Ueda — Shadow of the Colossus, ICO, The Last Guardian',
    mood: 'bleached sunlight, colossal ancient ruins on windswept plains, melancholy grandeur',
    kinds: ['terran', 'barren'],
    palette: { sky: '#cfd8dc', zenith: '#8ea6b4', horizon: '#eef0ea', fog: '#dfe3dc', sun: '#fffdf0',
      ground: ['#9aa070', '#b6b07c', '#7f8a5c', '#c9c29a'], rock: '#9b968a', sand: '#d8cfb0', water: '#5a7f8a',
      foliage: ['#7c8a4e', '#98a35e', '#5d6b3c'], accent: '#e8e2c8', lights: '#ffe6b0' },
    atmo: { rayleigh: [0.25, 0.4, 0.75], density: 1.0, mie: 0.8, mieColor: '#fffaf0', haze: 0.65 },
    terrain: { style: 'plateaus', relief: 0.9, ocean: 0.1, roughness: 0.5 },
    architecture: 'ruins', flora: 'grassland', fauna: ['birds', 'colossi'], weather: ['clear', 'fog'],
    grade: { temperature: 0.06, contrast: 0.96, saturation: 0.78, lift: [0.03, 0.03, 0.03], bloomStrength: 0.12 },
    music: { root: 52, scale: 'aeolian', tempo: 58, timbre: 'strings' },
  },
  pandora: {
    name: 'Pandora', inspiration: 'James Cameron — Avatar; Roger Dean floating mountains',
    mood: 'primeval jungle that breathes light at night; floating mountains, cathedral trees',
    kinds: ['jungle', 'exotic', 'terran'],
    palette: { sky: '#7fc6d8', zenith: '#2f7fb0', horizon: '#cdeef0', fog: '#8fc8c0', sun: '#fff6e0',
      ground: ['#2f6b3a', '#3d7f42', '#1f4f30', '#5a8a3a'], rock: '#4f5a5a', sand: '#9a9a7a', water: '#1f6f7f',
      foliage: ['#2f8a4a', '#1f6a3a', '#5ab04a', '#3fa07a'], accent: '#3ff0ff', lights: '#7af7ff', glow: ['#38f6ff', '#c04bff', '#5aff9a'] },
    atmo: { rayleigh: [0.16, 0.45, 0.9], density: 1.25, mie: 0.7, mieColor: '#e0fff8', haze: 0.6 },
    terrain: { style: 'karst', relief: 1.0, ocean: 0.2, roughness: 0.55 },
    architecture: 'organic', flora: 'bioluminescent', fauna: ['birds', 'jellies', 'grazers', 'fish'], weather: ['cumulus', 'rain', 'fog'],
    grade: { temperature: -0.02, contrast: 1.06, saturation: 1.18 },
    music: { root: 55, scale: 'lydian', tempo: 70, timbre: 'glass' },
  },
  bebop: {
    name: 'Tharsis Port', inspiration: 'Shinichirō Watanabe — Cowboy Bebop; Syd Mead; Blade Runner',
    mood: 'rust and neon, jazz drifting from canal bars, ships crossing a smoggy sunset',
    kinds: ['desert', 'terran', 'ocean', 'barren'],
    palette: { sky: '#e0905a', zenith: '#5a4a7a', horizon: '#ffc48a', fog: '#c8846a', sun: '#ffd0a0',
      ground: ['#a0603a', '#8a5030', '#b8784a', '#6a4a3a'], rock: '#704a3a', sand: '#c8946a', water: '#2a4a5a',
      foliage: ['#5a7a3a', '#3f6a4a'], accent: '#ff3f7f', lights: '#ff9f4a', neon: ['#ff2f8f', '#2fe0ff', '#ffd02f', '#9f5fff'] },
    atmo: { rayleigh: [0.5, 0.36, 0.42], density: 1.1, mie: 1.1, mieColor: '#ffb07a', haze: 0.8 },
    terrain: { style: 'canyons', relief: 0.7, ocean: 0.18, roughness: 0.45 },
    architecture: 'neon', flora: 'palms', fauna: ['birds'], weather: ['clear', 'rain'],
    grade: { temperature: 0.18, contrast: 1.1, saturation: 1.08, shadowsTint: [0.0, -0.005, 0.02], highlightsTint: [0.03, 0.01, -0.01] },
    music: { root: 53, scale: 'jazz', tempo: 88, timbre: 'jazz' },
  },
  erdtree: {
    name: 'The Lands Between', inspiration: 'FromSoftware — Elden Ring, Dark Souls; Kentaro Miura',
    mood: 'golden autumn forests beneath a colossal luminous tree; gothic ruins, mist, legend',
    kinds: ['terran', 'jungle'],
    palette: { sky: '#d8c08a', zenith: '#7a8aa0', horizon: '#f2dca8', fog: '#cdb88a', sun: '#ffe7a8',
      ground: ['#7a7040', '#8a7a3a', '#5a5a34', '#a08a4a'], rock: '#7a7468', sand: '#b8a67a', water: '#3a5a5a',
      foliage: ['#c89a2a', '#e0b040', '#a07020', '#7a8a3a'], accent: '#ffd25a', lights: '#ffc860', glow: ['#ffd76a'] },
    atmo: { rayleigh: [0.32, 0.38, 0.55], density: 1.1, mie: 1.0, mieColor: '#ffe6a8', haze: 0.75 },
    terrain: { style: 'highlands', relief: 1.0, ocean: 0.15, roughness: 0.55 },
    architecture: 'gothic', flora: 'golden', fauna: ['birds', 'grazers'], weather: ['clear', 'fog'],
    grade: { temperature: 0.2, contrast: 1.08, saturation: 0.95, bloomStrength: 0.1, highlightsTint: [0.03, 0.02, -0.02] },
    music: { root: 50, scale: 'harmonicMinor', tempo: 60, timbre: 'choir' },
  },
  wukong: {
    name: 'Mount Huaguo', inspiration: 'Black Myth: Wukong, Sekiro, Nine Sols; Song-dynasty shan shui painting',
    mood: 'misty karst pillars, crimson maples, temples clinging to cliffs, ink-wash mountains',
    kinds: ['terran', 'jungle'],
    palette: { sky: '#c8d0cc', zenith: '#7a8e98', horizon: '#eaeee6', fog: '#c6cec8', sun: '#fff2dc',
      ground: ['#5a6a44', '#4a5a3a', '#6a7a4a', '#8a8a62'], rock: '#6a6a66', sand: '#b0a88a', water: '#4a6a6a',
      foliage: ['#b8322a', '#d8642a', '#3f5a34', '#e8a83a'], accent: '#c8282a', lights: '#ffb85a' },
    atmo: { rayleigh: [0.24, 0.36, 0.6], density: 1.2, mie: 1.3, mieColor: '#f4f4ee', haze: 1.0 },
    terrain: { style: 'karst', relief: 1.2, ocean: 0.2, roughness: 0.6 },
    architecture: 'temple', flora: 'maple', fauna: ['birds', 'cranes', 'fish'], weather: ['fog', 'clear', 'rain'],
    grade: { temperature: 0.0, contrast: 1.04, saturation: 0.82, lift: [0.02, 0.02, 0.02] },
    music: { root: 55, scale: 'pentatonic', tempo: 56, timbre: 'pluck' },
  },
  interstellar: {
    name: 'Miller', inspiration: 'Christopher Nolan — Interstellar; Solaris',
    mood: 'an endless shallow ocean under a vast ringed gas giant; mountains that are waves',
    kinds: ['ocean', 'ice'],
    palette: { sky: '#a8b8c0', zenith: '#5a7080', horizon: '#dde4e6', fog: '#b8c4c8', sun: '#fffaf2',
      ground: ['#7a7e80', '#8a8a86', '#5a5e60', '#a0a29a'], rock: '#5c6266', sand: '#b8b4a6', water: '#3a6670',
      foliage: ['#4a5a4a'], accent: '#f0f0f0', lights: '#e0f0ff' },
    atmo: { rayleigh: [0.22, 0.34, 0.5], density: 1.1, mie: 0.9, mieColor: '#ffffff', haze: 0.8 },
    terrain: { style: 'archipelago', relief: 0.5, ocean: 0.75, roughness: 0.4 },
    architecture: 'outpost', flora: 'sparse', fauna: ['fish'], weather: ['fog', 'clear'],
    grade: { temperature: -0.08, contrast: 1.06, saturation: 0.72 },
    music: { root: 48, scale: 'aeolian', tempo: 50, timbre: 'organ' },
  },
  rick: {
    name: 'Dimension C-137', inspiration: 'Rick and Morty; Adventure Time; Fantastic Planet',
    mood: 'gloriously weird: candy-colored skies, bulbous towers, creatures that should not exist',
    kinds: ['exotic', 'toxic', 'jungle'],
    palette: { sky: '#a8f070', zenith: '#40c0a0', horizon: '#f0ffb0', fog: '#c0f090', sun: '#fff0ff',
      ground: ['#8a3fd0', '#b04fe0', '#6a2fb0', '#d07af0'], rock: '#3f8a8a', sand: '#f0a0d0', water: '#ff7ad0',
      foliage: ['#ff5fa0', '#ffd03f', '#3fe0ff', '#7fff5f'], accent: '#3fffb0', lights: '#ffff7a', glow: ['#ff4fd8', '#4fffe0'] },
    atmo: { rayleigh: [0.6, 1.0, 0.4], density: 1.0, mie: 0.4, mieColor: '#f0ffd0', haze: 0.4 },
    terrain: { style: 'blobby', relief: 0.8, ocean: 0.25, roughness: 0.3 },
    architecture: 'organic', flora: 'alien', fauna: ['blobs', 'jellies', 'walkers'], weather: ['clear'],
    grade: { temperature: 0.0, contrast: 1.05, saturation: 1.3 },
    music: { root: 62, scale: 'wholetone', tempo: 96, timbre: 'synth' },
  },
  nausicaa: {
    name: 'Sea of Corruption', inspiration: 'Hayao Miyazaki — Nausicaä of the Valley of the Wind',
    mood: 'a toxic jungle of giant fungi raining spores, beautiful and lethal; a windmill valley at its edge',
    kinds: ['toxic', 'jungle'],
    palette: { sky: '#c8c890', zenith: '#7a9a8a', horizon: '#ece8b8', fog: '#c0c49a', sun: '#fff6cc',
      ground: ['#6a7a4a', '#8a8a5a', '#4a5a3a', '#a09a6a'], rock: '#6a6a5a', sand: '#c0b88a', water: '#5a7a6a',
      foliage: ['#c8b84a', '#8ab04a', '#d8d08a', '#5aa08a'], accent: '#e0d040', lights: '#fff0a0', glow: ['#c0ff8a', '#e0f0ff'] },
    atmo: { rayleigh: [0.4, 0.45, 0.42], density: 1.2, mie: 1.4, mieColor: '#f0f0c8', haze: 1.0 },
    terrain: { style: 'rolling', relief: 0.6, ocean: 0.12, roughness: 0.5 },
    architecture: 'pastoral', flora: 'fungal', fauna: ['insects', 'birds'], weather: ['spores', 'fog'],
    grade: { temperature: 0.06, contrast: 1.0, saturation: 0.92 },
    music: { root: 57, scale: 'dorian', tempo: 62, timbre: 'strings' },
  },
  frontier: {
    name: 'Kepler Frontier', inspiration: 'Starfield & NASA-punk; The Expanse; Syd Mead hard sci-fi',
    mood: 'rugged alien badlands, modular habitats, landing pads, a frontier humming with industry',
    kinds: ['barren', 'desert', 'ice', 'lava'],
    palette: { sky: '#9ab0c8', zenith: '#3a5a88', horizon: '#d8e0e8', fog: '#a8b4c0', sun: '#fff8ee',
      ground: ['#8a7a6a', '#6a5e52', '#a0907a', '#5a524a'], rock: '#5a5048', sand: '#b0a08a', water: '#2a4a6a',
      foliage: ['#5a6a4a'], accent: '#ff8a2a', lights: '#cfe6ff' },
    atmo: { rayleigh: [0.22, 0.36, 0.8], density: 0.6, mie: 0.4, mieColor: '#f0e8e0', haze: 0.35 },
    terrain: { style: 'badlands', relief: 0.9, ocean: 0.0, roughness: 0.6 },
    architecture: 'outpost', flora: 'sparse', fauna: ['walkers'], weather: ['clear', 'dust'],
    grade: { temperature: 0.0, contrast: 1.1, saturation: 0.9 },
    music: { root: 52, scale: 'mixolydian', tempo: 72, timbre: 'synth' },
  },
  inferno: {
    name: 'Mustafar', inspiration: 'Star Wars — Mustafar; Dante; Zdzisław Beksiński',
    mood: 'rivers of lava under an ash-black sky; obsidian fortresses lit from below',
    kinds: ['lava'],
    palette: { sky: '#2a1410', zenith: '#0a0606', horizon: '#6a2a14', fog: '#3a1a12', sun: '#ffb070',
      ground: ['#1a1414', '#2a1e1a', '#3a2a22', '#120e0e'], rock: '#221a18', sand: '#3a2a20', water: '#ff5a10',
      foliage: ['#3a2a20'], accent: '#ff5a10', lights: '#ff8a3a', glow: ['#ff4a10', '#ffb030'] },
    atmo: { rayleigh: [0.6, 0.3, 0.2], density: 1.3, mie: 1.6, mieColor: '#ff8a50', haze: 1.0 },
    terrain: { style: 'volcanic', relief: 1.0, ocean: 0.12, roughness: 0.7 },
    architecture: 'monolithic', flora: 'none', fauna: [], weather: ['ash'],
    grade: { temperature: 0.3, contrast: 1.18, saturation: 1.0, blackPoint: 0.008 },
    music: { root: 43, scale: 'phrygian', tempo: 48, timbre: 'drone' },
  },
  glacier: {
    name: 'Hoth', inspiration: 'The Empire Strikes Back — Hoth; Caspar David Friedrich; Shackleton',
    mood: 'blue ice cathedrals, auroras over frozen seas, a lone lantern-lit research village',
    kinds: ['ice'],
    palette: { sky: '#b8d0e8', zenith: '#4a78b0', horizon: '#eef6ff', fog: '#d0e0f0', sun: '#fffaf0',
      ground: ['#e8f0f8', '#d0e0ee', '#b8cce0', '#f8fbff'], rock: '#5a6878', sand: '#dfe8f0', water: '#1f4a6a',
      foliage: ['#3a5a5a', '#2a4a4a'], accent: '#5ae0ff', lights: '#ffd8a0', glow: ['#5affb0', '#8a7aff'] },
    atmo: { rayleigh: [0.18, 0.4, 1.0], density: 0.9, mie: 0.5, mieColor: '#ffffff', haze: 0.5 },
    terrain: { style: 'glacial', relief: 0.85, ocean: 0.3, roughness: 0.5 },
    architecture: 'outpost', flora: 'boreal', fauna: ['birds', 'grazers'], weather: ['snow', 'clear', 'aurora'],
    grade: { temperature: -0.15, contrast: 1.05, saturation: 0.9 },
    music: { root: 59, scale: 'lydian', tempo: 52, timbre: 'glass' },
  },
};

export const AESTHETIC_IDS = Object.keys(AESTHETICS);

/** Pick an aesthetic for a planet kind, deterministically from rng. */
export function aestheticFor(kind, rng) {
  const fits = AESTHETIC_IDS.filter((id) => AESTHETICS[id].kinds.includes(kind));
  return fits.length ? rng.pick(fits) : rng.pick(AESTHETIC_IDS);
}
